import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "../../components/Sidebar/Sidebar";
import { Providers } from "@/components/Providers/Providers";
import Header from "@/components/Header/Header";

import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header>
            <Header />
          </header>
          <main>
            <div className="container mx-auto grid grid-cols-4 gap-4">
              <Sidebar />
              <div className="col-span-3 min-h-[fit-content]">{children}</div>
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
