import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import Sidebar from "../../../components/Sidebar/Sidebar";
import { Providers } from "@/components/Providers/Providers";
// import Header from "@/components/Header/Header";

import "@/styles/globals.css";
// import Header from "@/components/Header/Header";
// import { ReactNode } from "react";
// import Sidebar from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex min-h-screen flex-col">{children}</div>
          {/* <div id="overlay" /> */}
        </Providers>
      </body>
    </html>
  );
}

// params: { locale },
// ang={locale}
