import { Inter } from 'next/font/google'
import '../../styles/globals.css'
import { ReactNode } from 'react'
import { Providers } from '@/components/Providers/Providers'
import Header from '@/components/Header/Header'
import { locales } from '@/config'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

type Props = {
    children: ReactNode
    params: { locale: string }
}

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children, params: { locale } }: Props) {
    return (
        <html lang={locale}>
            <body className={inter.className}>
                <Providers>
                    <header>
                        <Header />
                    </header>
                    {children}
                </Providers>
            </body>
        </html>
    )
}
