import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "../../../components/Sidebar/Sidebar";
import { Providers } from "@/components/Providers/Providers";
import Header from "@/components/Header/Header";

import "@/styles/globals.css";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout(props: { children: ReactNode }) {
  return (
    <div className="container mx-auto grid grid-cols-4 gap-4">
      <Sidebar />
      <div className="col-span-3 min-h-[fit-content]">{props.children}</div>
    </div>
  );
}
